### ISSUE TITLE
Identify the Dangerous URL

### ISSUE THREAD

**Issue by jonathansampson** [phishfort/protect#21]
This warning informs the user they may be on their way to a dangerous site, allows them to proceed anyway, but never tells them the URL they're about to visit. This is a good opportunity for users to realize they are following a typo-squatter link, or may have even typed the URL incorrectly themselves.

My suggestion would be to cleanly display the URL for the user, which may help them spot a typo. It may even be good to check the Levenshtein Distance against _known-good_ URLs and use that to indicate whether the URL may be impersonating a trusted site:

![should-show-the-URL-in-clear-font-for-user](https://user-images.githubusercontent.com/815158/92269210-5d466680-eea9-11ea-8ea9-8fcc3f7e6b1e.JPG)

**Comment by korn101** [comment]
Included in commit [a4a2b5](https://github.com/phishfort/protect/commit/a4a2b52fbc3b5669df6d89cd67821547f69b6b93) for latest deployment.
